apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-signup-form
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-signup-form
  template:
    metadata:
      labels:
        app: login-signup-form
    spec:
      containers:
        - name: login-signup-form-container
          image: 'rishithamarri/login-signup-form:'
          ports:
            - containerPort: 80
